version: '3.8'

services:
  db:
    image: postgres:15
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: mydatabase
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  web:
    build:
      context: .   # Ensure it looks in the current directory
      dockerfile: Dockerfile  # Explicitly define the Dockerfile
    container_name: flask_app
    restart: always
    depends_on:
      - db
    environment:
      DATABASE_URL: postgresql://myuser:mypassword@db:5432/mydatabase
      FLASK_APP: main.py
      FLASK_ENV: production
    ports:
      - "5001:5000"
    volumes:
      - .:/app
    command: ["flask", "run", "--host=0.0.0.0", "--port=5000"]

volumes:
  postgres_data: