version: '3.8'

services:
  db:
    image: postgres:15
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: mydatabase
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U myuser -d mydatabase"]
      interval: 5s
      retries: 5
      timeout: 3s

  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: flask_app
    restart: always
    depends_on:
      db:
        condition: service_healthy  # Ensures the database is fully ready
    environment:
      DATABASE_URL: postgresql://myuser:mypassword@db:5432/mydatabase
      FLASK_APP: main.py
      FLASK_ENV: production
    ports:
      - "5001:5000"
    volumes:
      - .:/app
    command: ["/bin/sh", "-c", "flask db upgrade && flask run --host=0.0.0.0 --port=5000"]

volumes:
  postgres_data:
